server:
  port: 10086
eureka:
   instance:
     hostname: slave1
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://slave1:10087/eureka/
spring:
  application:
    name: eurekaserver_one