server:
  port: 10086
eureka:
   instance:
     hostname: slave1
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://slave2:10087/eureka/
spring:
  application:
    name: eurekaserver_one