server:
  port: 10091
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/xml,text/html,text/plain
    min-response-size: 1

eureka:
 client:
   service-url:
     defaultZone: http://slave1:10086/eureka/,http://slave2:10087/eureka/
spring:
    application:
      name: consumer_one
      
feign:
  hystrix:
    enabled: true