
server:
  port: 10010

eureka:
  #instance:
    #eureka服务端的实例名称
    #hostname: producter
  client:
    # false表示不向注册中心注册自己
    # register-with-eureka: true
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    # fetch-registry: true
    service-url:
      defaultZone: http://slave1:10086/eureka/,http://slave2:10087/eureka/
spring:
    application:
      name: producter