server:
   port: 10087

eureka:
  instance:
     #eureka服务端的实例名称
    hostname: slave2
  client:
    # false表示不向注册中心注册自己
    registerWithEureka: true
     # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://slave1:10086/eureka/

spring:
  application:
    name: eurekaserver_two
